In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn import svm
from sklearn.metrics import (accuracy_score, recall_score, f1_score, confusion_matrix, classification_report, precision_score)
from sklearn.linear_model import LogisticRegression
from sklearn import preprocessing
from sklearn.preprocessing import StandardScaler

In [2]:
df = pd.read_csv("heart_failure_clinical_records_dataset.csv")

In [3]:
df.head()

,age,anaemia,creatinine_phosphokinase,diabetes,ejection_fraction,high_blood_pressure,platelets,serum_creatinine,serum_sodium,sex,smoking,time,DEATH_EVENT
0,75.0,0,582,0,20,1,265000.00,1.9,130,1,0,4,1
1,55.0,0,7861,0,38,0,263358.03,1.1,136,1,0,6,1
2,65.0,0,146,0,20,0,162000.00,1.3,129,1,1,7,1
3,50.0,1,111,0,20,0,210000.00,1.9,137,1,0,7,1
4,65.0,1,160,1,20,0,327000.00,2.7,116,0,0,8,1

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 299 entries, 0 to 298
Data columns (total 13 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   age                       299 non-null    float64
 1   anaemia                   299 non-null    int64
 2   creatinine_phosphokinase  299 non-null    int64
 3   diabetes                  299 non-null    int64
 4   ejection_fraction         299 non-null    int64
 5   high_blood_pressure       299 non-null    int64
 6   platelets                 299 non-null    float64
 7   serum_creatinine          299 non-null    float64
 8   serum_sodium              299 non-null    int64
 9   sex                       299 non-null    int64
 10  smoking                   299 non-null    int64
 11  time                      299 non-null    int64
 12  DEATH_EVENT               299 non-null    int64
dtypes: float64(3), int64(10)
memory usage: 30.5 KB

In [5]:
df.describe()

,age,anaemia,creatinine_phosphokinase,diabetes,ejection_fraction,high_blood_pressure,platelets,serum_creatinine,serum_sodium,sex,smoking,time,DEATH_EVENT
count,299.000000,299.000000,299.000000,299.000000,299.000000,299.000000,299.000000,299.00000,299.000000,299.000000,299.00000,299.000000,299.00000
mean,60.833893,0.431438,581.839465,0.418060,38.083612,0.351171,263358.029264,1.39388,136.625418,0.648829,0.32107,130.260870,0.32107
std,11.894809,0.496107,970.287881,0.494067,11.834841,0.478136,97804.236869,1.03451,4.412477,0.478136,0.46767,77.614208,0.46767
min,40.000000,0.000000,23.000000,0.000000,14.000000,0.000000,25100.000000,0.50000,113.000000,0.000000,0.00000,4.000000,0.00000
25%,51.000000,0.000000,116.500000,0.000000,30.000000,0.000000,212500.000000,0.90000,134.000000,0.000000,0.00000,73.000000,0.00000
50%,60.000000,0.000000,250.000000,0.000000,38.000000,0.000000,262000.000000,1.10000,137.000000,1.000000,0.00000,115.000000,0.00000
75%,70.000000,1.000000,582.000000,1.000000,45.000000,1.000000,303500.000000,1.40000,140.000000,1.000000,1.00000,203.000000,1.00000
max,95.000000,1.000000,7861.000000,1.000000,80.000000,1.000000,850000.000000,9.40000,148.000000,1.000000,1.00000,285.000000,1.00000

In [6]:
df.isnull().sum()

age                         0
anaemia                     0
creatinine_phosphokinase    0
diabetes                    0
ejection_fraction           0
high_blood_pressure         0
platelets                   0
serum_creatinine            0
serum_sodium                0
sex                         0
smoking                     0
time                        0
DEATH_EVENT                 0
dtype: int64

In [7]:
X = df.drop(['DEATH_EVENT'], axis = 1)
y = df['DEATH_EVENT']

In [8]:
col_names = list(X.columns)
s_scaler = preprocessing.StandardScaler()
x_scaled = s_scaler.fit_transform(X)
x_scaled = pd.DataFrame(x_scaled, columns = col_names)
x_scaled.describe().T

,count,mean,std,min,25%,50%,75%,max
age,299.0,5.703353e-16,1.001676,-1.754448,-0.828124,-0.070223,0.771889,2.877170
anaemia,299.0,1.009969e-16,1.001676,-0.871105,-0.871105,-0.871105,1.147968,1.147968
creatinine_phosphokinase,299.0,0.000000e+00,1.001676,-0.576918,-0.480393,-0.342574,0.000166,7.514640
diabetes,299.0,9.060014e-17,1.001676,-0.847579,-0.847579,-0.847579,1.179830,1.179830
ejection_fraction,299.0,-3.267546e-17,1.001676,-2.038387,-0.684180,-0.007077,0.585389,3.547716
high_blood_pressure,299.0,0.000000e+00,1.001676,-0.735688,-0.735688,-0.735688,1.359272,1.359272
platelets,299.0,7.723291e-17,1.001676,-2.440155,-0.520870,-0.013908,0.411120,6.008180
serum_creatinine,299.0,1.425838e-16,1.001676,-0.865509,-0.478205,-0.284552,0.005926,7.752020
serum_sodium,299.0,-8.673849e-16,1.001676,-5.363206,-0.595996,0.085034,0.766064,2.582144
sex,299.0,-8.911489e-18,1.001676,-1.359272,-1.359272,0.735688,0.735688,0.735688
smoking,299.0,-1.188199e-17,1.001676,-0.687682,-0.687682,-0.687682,1.454161,1.454161
time,299.0,-1.901118e-16,1.001676,-1.629502,-0.739000,-0.196954,0.938759,1.997038

In [10]:
X_train, X_test, y_train, y_test = train_test_split(x_scaled, y, test_size = 0.3, random_state=42)

In [19]:
print("Evaluation of SVM Model")
svm_model = svm.SVC(kernel = "linear")
svm_model.fit(X_train, y_train)
svm_pred = svm_model.predict(X_test)
svm_accuracy = accuracy_score(y_test, svm_pred)
svm_recall = recall_score(y_test, svm_pred)
svm_precision = precision_score(y_test, svm_pred)
svm_f1 = f1_score(y_test, svm_pred)

Evaluation of SVM Model

In [20]:
print("prediction", svm_pred)
print("="*100)
print("Accuracy: ",f"{(svm_accuracy * 100)}%")
print("recall: ",f"{(svm_recall * 100)}%")
print("precision: ",f"{(svm_precision * 100)}%")
print("f1: ",f"{(svm_f1 * 100)}%")

prediction [0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 1 0 1 1 1 0 0
 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 1 0 0 0 1 1 0 1 0 0 1 1 0 0
 0 0 0 1 0 0 0 1 0 0 0 0 1 1 1 0]
====================================================================================================
Accuracy:  76.66666666666667%
recall:  51.35135135135135%
precision:  86.36363636363636%
f1:  64.40677966101694%

In [21]:
print("Confusion matrix: ")
print(confusion_matrix(y_test, svm_pred))

Confusion matrix:
[[50  3]
 [18 19]]

In [22]:
print("Classification Report: ")
print(classification_report(y_test, svm_pred))

Classification Report:
              precision    recall  f1-score   support

           0       0.74      0.94      0.83        53
           1       0.86      0.51      0.64        37

    accuracy                           0.77        90
   macro avg       0.80      0.73      0.74        90
weighted avg       0.79      0.77      0.75        90

In [24]:
print("Evaluation of KNN")
knn_model = KNeighborsClassifier(n_neighbors = 5)
knn_model.fit(X_train, y_train)
knn_pred = knn_model.predict(X_test)
knn_accuracy=accuracy_score(y_test,knn_pred)
knn_recall = recall_score(y_test,knn_pred)
knn_precision = precision_score(y_test, knn_pred)
knn_f1 = f1_score(y_test, knn_pred)

Evaluation of KNN

In [25]:
print("prediction: ",knn_pred)
print("Accuracy: ",f"{(knn_accuracy * 100)}%")
print("Recall: ",f"{(knn_recall * 100)}%")
print("Precision: ",f"{(knn_precision * 100)}%")
print("F1: ",f"{(knn_f1 * 100)}%")

prediction:  [0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 1 1 0 0 0 1 1 0 0 0 0 0 0 0 0
 1 0 0 0 0 0 0 1 0 0 0 0 0 1 1 0]
Accuracy:  70.0%
Recall:  32.432432432432435%
Precision:  85.71428571428571%
F1:  47.05882352941176%

In [27]:
print("Confusion_matrix: ")
print(confusion_matrix(y_test, knn_pred))

Confusion_matrix:
[[51  2]
 [25 12]]

In [28]:
print("Classification report: ")
print(classification_report(y_test,knn_pred))

Classification report:
              precision    recall  f1-score   support

           0       0.67      0.96      0.79        53
           1       0.86      0.32      0.47        37

    accuracy                           0.70        90
   macro avg       0.76      0.64      0.63        90
weighted avg       0.75      0.70      0.66        90

In [32]:
print("Evaluation of Logistic Regression: ")
log_model = LogisticRegression()
log_model.fit(X_train, y_train)
log_pred = log_model.predict(X_test)
log_accuracy = accuracy_score(y_test, log_pred)
log_recall = recall_score(y_test, log_pred)
log_precision = precision_score(y_test, log_pred)
log_f1 = f1_score(y_test, log_pred)

Evaluation of Logistic Regression:

In [33]:
print("Prediction: ", log_model)
print("Accuracy: ",f"{(log_accuracy*100)}%")
print("Recall: ",f"{(log_recall*100)}%")
print("Precision: ", f"{(log_precision*100)}%")
print("F1: ",f"{(log_f1*100)}%")

Prediction:  LogisticRegression()
Accuracy:  78.88888888888889%
Recall:  56.75675675675676%
Precision:  87.5%
F1:  68.85245901639344%

In [35]:
print("Confusion matrix:")
print(confusion_matrix(y_test, log_pred))

Confusion matrix:
[[50  3]
 [16 21]]

In [36]:
print("Classification Report")
print(classification_report(y_test, log_pred))

Classification Report
              precision    recall  f1-score   support

           0       0.76      0.94      0.84        53
           1       0.88      0.57      0.69        37

    accuracy                           0.79        90
   macro avg       0.82      0.76      0.76        90
weighted avg       0.81      0.79      0.78        90